NMS-14674: API abstraction layer
OpenNMS/opennms-velocloud-plugin pull request #10
Opened 2022-08-30 14:36 UTC by fooker

2022-08-30 15:56 UTC, aramosvizcarra requested changes
A couple of minor changes everything else looks good!

2022-08-30 15:56 UTC, aramosvizcarra commented on client/v1/src/test/java/org/opennms/velocloud/client/v1/VelocloudApiClientV1Test.java
> +import static org.junit.Assert.*;
I think we should avoit this multiple imports \*

2022-08-30 15:56 UTC, aramosvizcarra commented on client/v2/src/test/java/org/opennms/velocloud/client/v2/VelocloudApiClientV2Test.java
>  import static org.junit.Assert.*;
I probably missed this as well. It would be better if we just can just import what we are using.

2022-08-30 16:07 UTC, aramosvizcarra commented
Looks like there is an issue in the features.xml

 Unable to resolve org.opennms.plugins.velocloud.plugin/0.1.0.SNAPSHOT: missing requirement [org.opennms.plugins.velocloud.plugin/0.1.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.opennms.velocloud.client.api.VelocloudApiClient)

2022-08-31 08:34 UTC, fooker commented
> Looks like there is an issue in the features.xml
> 
> Unable to resolve org.opennms.plugins.velocloud.plugin/0.1.0.SNAPSHOT: missing requirement [org.opennms.plugins.velocloud.plugin/0.1.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=org.opennms.velocloud.client.api.VelocloudApiClient)

Resolved. Looks like there is no (easy) way to have a service from a nested class/interface.

2022-08-31 12:16 UTC, aramosvizcarra approved these changes
LGTM!

2022-08-31 12:23 UTC, amay94 approved these changes

2022-08-31 13:03 UTC, merged