NMS-14594: Implement gateway status poller
OpenNMS/opennms-velocloud-plugin pull request #24
Opened 2022-10-26 12:52 UTC by fooker

https://issues.opennms.org/browse/NMS-14594

2022-10-26 16:21 UTC, aramosvizcarra submitted a review, later dismissed
LGTM

2022-11-01 09:56 UTC, christianpape requested changes

2022-11-01 09:56 UTC, christianpape commented on README.md
> +
```suggestion
To speed up development iterations, one can use `-Dcodegen.skip=true` to skip the re-generation of the client model classes.

```

2022-11-01 17:19 UTC, aramosvizcarra approved these changes

2022-11-02 11:03 UTC, christianpape approved these changes
LGTM.

2022-11-02 14:57 UTC, merged