NMS-14511:Velocloud API interaction baselines API v2
OpenNMS/opennms-velocloud-plugin pull request #3
Opened 2022-07-19 20:57 UTC by aramosvizcarra

Initial Client API generated with swagger code generator and okhttp3-gson library (default)

Needed some manual fix since swagger generator uses an old version of okhttp.

Added the swagger module in case we want to revisit another library (eg. resttemplate works)

[Swagger generator](https://github.com/swagger-api/swagger-codegen) seems a better option anyways than [OpenAPITools](https://github.com/OpenAPITools/openapi-generator) since the last one has issues supporting some openapi features and swagger is mainly oudated dependencies. There is a [PR](https://github.com/JackOfMostTrades/swagger-codegen.git ) I was trying to build that is supposed to update okhttp to okhttp3. Although I was having some issues with it and couldn't make it  work yet. I'll probably revisit that  tomorrow.

2022-07-20 20:09 UTC, aramosvizcarra commented
- Added a new karaf bundle that contains all the generated client API. 
- Automated swagger-generator to generate and copy the code generated into the client bundle.
- Modified swagger library type to **resttemplate** 
To generate the client api code just do a **mvn clean install**

2022-07-20 20:12 UTC, aramosvizcarra commented
Things to be done would be 
-wiring the api to the plugin. 
-adding license to java classes (at some point, if we continue with automation probably add the license as a final step)
-Start adding unit tests.

2022-07-26 13:32 UTC, fooker requested changes

2022-07-26 13:32 UTC, fooker commented on pom.xml
> +        <maven.compiler.target>11</maven.compiler.target>
This also conflicts with `java.version`

2022-07-26 13:53 UTC, merged