NMS-14498: Parameter to controll requisition location
OpenNMS/opennms-velocloud-plugin pull request #37
Opened 2023-01-17 14:40 UTC by fooker

2023-01-17 15:06 UTC, amay94 submitted a review, later dismissed

2023-01-17 15:23 UTC, aramosvizcarra requested changes
To small changes

2023-01-17 15:23 UTC, aramosvizcarra commented on plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
> +                                                     .setNodeLabel(context.getLocation());
```suggestion
                                                     .setLocation(context.getLocation());
```

2023-01-17 15:23 UTC, aramosvizcarra commented on plugin/src/main/java/org/opennms/velocloud/requisition/PartnerRequisitionProvider.java
> +                                                         .setNodeLabel(context.getLocation());
```suggestion
                                                         .setLocation(context.getLocation());
```

2023-01-17 15:26 UTC, aramosvizcarra reviewed
Shouldn't the license be now 2023?

2023-01-18 09:49 UTC, fooker commented on plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
> +                                                     .setNodeLabel(context.getLocation());
Fixed

2023-01-18 13:14 UTC, amay94 submitted a review, later dismissed

2023-01-18 13:16 UTC, christianpape submitted a review, later dismissed
LGTM.

2023-01-18 14:02 UTC, Bonrob2 reviewed
Just a minor change to minimize the number of times we say "default". :-)

2023-01-18 14:02 UTC, Bonrob2 commented on docs/modules/configuration/pages/requisitions.adoc
> +All nodes created by a requisition are assigned to the same location controlled by the `location' parameter, which defaults to the default location if not specified.
```suggestion
All nodes created by a requisition are assigned to the same location controlled by the `location' parameter, which uses the default location if not specified.
```

2023-01-18 14:43 UTC, aramosvizcarra approved these changes

2023-01-24 12:52 UTC, christianpape submitted a review, later dismissed
LGTM.

2023-01-24 14:01 UTC, Bonrob2 approved these changes
Docs LGTM!

2023-02-21 14:36 UTC, christianpape submitted a review, later dismissed
LGTM.

2023-02-28 14:46 UTC, christianpape approved these changes

2023-02-28 14:47 UTC, merged