VP-44: Added false-positive Edge status check
OpenNMS/opennms-velocloud-plugin pull request #39
Opened 2023-02-02 07:41 UTC by christianpape

* JIRA: https://opennms.atlassian.net/browse/VP-44

2023-02-02 14:14 UTC, aramosvizcarra requested changes
Just a couple of small changes... Otherwise Looks good to me

2023-02-02 14:14 UTC, aramosvizcarra commented on plugin/src/main/java/org/opennms/velocloud/pollers/edge/EdgeManagementStatusPoller.java
> +package org.opennms.velocloud.pollers.edge;
I think you are missing a license here

2023-02-02 14:14 UTC, aramosvizcarra commented on plugin/src/main/java/org/opennms/velocloud/pollers/edge/EdgeManagementStatusPollerFactory.java
> +package org.opennms.velocloud.pollers.edge;
Same missing license

2023-02-02 16:27 UTC, aramosvizcarra approved these changes
LGTM

2023-02-07 14:05 UTC, christianpape commented on plugin/src/main/java/org/opennms/velocloud/pollers/edge/EdgeManagementStatusPollerFactory.java
> +package org.opennms.velocloud.pollers.edge;
Fixed.

2023-02-09 09:57 UTC, fooker requested changes

2023-02-09 09:57 UTC, fooker commented on plugin/src/main/java/org/opennms/velocloud/events/VelocloudEventIngestor.java
> +            alias = map.get("alias");
Please add non-null checks.

2023-02-09 09:57 UTC, fooker commented on plugin/src/main/java/org/opennms/velocloud/events/VelocloudEventIngestor.java
> +                    .anyMatch(metaData -> Objects.equals(AbstractRequisitionProvider.VELOCLOUD_METADATA_CONTEXT, metaData.getContext())))
Can we filter on nodes having the `alias` attribute set here?

2023-02-09 09:57 UTC, fooker commented on plugin/src/main/java/org/opennms/velocloud/events/VelocloudEventIngestor.java
> +            Optional<VelocloudApiCustomerClient> velocloudApiCustomerClient = Optional.empty();
Can be simplified.

2023-02-09 09:57 UTC, fooker commented on plugin/src/main/java/org/opennms/velocloud/events/VelocloudEventIngestor.java
> +                    LOG.debug("Error creating customer connection for the given credentials: {}", requisitionIdentifier.alias);
Log as error?

2023-02-09 09:57 UTC, fooker commented on plugin/src/main/java/org/opennms/velocloud/events/VelocloudEventIngestor.java
>                  LOG.debug("ignoring enterprise event #{} due to missing edgeName.", customerEvent.getId());
Can be removed.

2023-02-09 09:57 UTC, fooker commented on plugin/src/main/java/org/opennms/velocloud/events/VelocloudEventIngestor.java
>                  LOG.debug("ignoring proxy event #{} due to missing gatewayName.", partnerEvent.getId());
Same here.

2023-02-09 09:57 UTC, fooker commented on plugin/src/main/java/org/opennms/velocloud/pollers/AbstractStatusPoller.java
> +                return AbstractStatusPoller.this.clientManager.getCustomerClient(this.getClientCredentials());
Can we move this to the connection manager and re-use in the event processor?

2023-02-09 14:50 UTC, fooker approved these changes

2023-02-10 10:34 UTC, merged