VP-59: Allow to set foreignSource for requisitions
OpenNMS/opennms-velocloud-plugin pull request #42
Opened 2023-02-14 13:39 UTC by christianpape

* JIRA: https://opennms.atlassian.net/browse/VP-59

2023-02-14 14:08 UTC, Bonrob2 requested changes
Minor changes to the docs. Thank you!

2023-02-14 14:08 UTC, Bonrob2 commented on docs/modules/configuration/pages/requisitions.adoc
> +You can specify an additional parameter `foreignSource` to set the foreign source and requisition name.
```suggestion
You can specify an additional parameter, `foreignSource`, to set the foreign source and requisition name.
```

2023-02-14 14:08 UTC, Bonrob2 commented on docs/modules/configuration/pages/requisitions.adoc
> +The following example will create a customer requisition named `My-Customer-Requisition`.
```suggestion
The following example creates a customer requisition named `My-Customer-Requisition`.
```

2023-02-14 14:18 UTC, christianpape commented on docs/modules/configuration/pages/requisitions.adoc
> +You can specify an additional parameter `foreignSource` to set the foreign source and requisition name.
done.

2023-02-14 14:34 UTC, Bonrob2 approved these changes
docs LGTM! Thank you!

2023-02-14 15:51 UTC, aramosvizcarra approved these changes
LGTM

2023-02-14 15:54 UTC, fooker requested changes

2023-02-14 15:54 UTC, fooker commented on plugin/src/main/java/org/opennms/velocloud/requisition/PartnerRequisitionProvider.java
> +    public static final String PARAMETER_FOREIGN_SOURCE = "foreignSource";
Push it to the parent class?

2023-02-14 20:32 UTC, christianpape commented on plugin/src/main/java/org/opennms/velocloud/requisition/PartnerRequisitionProvider.java
> +    public static final String PARAMETER_FOREIGN_SOURCE = "foreignSource";
done.

2023-02-21 10:24 UTC, fooker approved these changes

2023-02-21 10:35 UTC, merged