VP-73: Velocloud docs omit instructions for adding plugin to features…
OpenNMS/opennms-velocloud-plugin pull request #52
Opened 2023-04-06 20:48 UTC by Bonrob2

…Boot.d

updated to add instructions for adding plugin to featuresBoot.d

2023-04-10 19:00 UTC, emarsh1995 requested changes
Some small formatting updates. Thanks!

2023-04-10 19:00 UTC, emarsh1995 commented on docs/modules/installation/pages/installation.adoc
> +echo "opennms-plugins-velocloud wait-for-kar=opennms-plugins-velocloud" | sudo tee ${OPENNMS_HOME}/etc/featuresBoot.d/plugin-velocloud.boot
```suggestion
[source, shell]
echo "opennms-plugins-velocloud wait-for-kar=opennms-plugins-velocloud" | sudo tee ${OPENNMS_HOME}/etc/featuresBoot.d/plugin-velocloud.boot
```

2023-04-10 19:00 UTC, emarsh1995 commented on docs/modules/installation/pages/installation.adoc
> +To ensure that the feature is activated on future service restarts, add the feature to a file in `featuresBoot.d`:
```suggestion

To ensure that the feature is activated on future service restarts, add the feature to a file in `featuresBoot.d`:
```

2023-04-11 07:03 UTC, christianpape approved these changes
LGTM.

2023-04-11 13:38 UTC, emarsh1995 approved these changes
LGTM. Thank you!

2023-04-11 13:40 UTC, merged