NMS-14677:Create Velocloud V1 client similar to current V2
OpenNMS/opennms-velocloud-plugin pull request #8
Opened 2022-08-24 12:48 UTC by aramosvizcarra

Added client to handle API V1and V2

2022-08-24 14:19 UTC, fooker requested changes

2022-08-24 14:19 UTC, fooker commented on client/v2/src/main/test/java/org/opennms/velocloud/client/v2/VelocloudApiClientTest.java
> -package org.opennms.velocloud;
The path of this file is wrong. Should be `src/test/java` not `src/main/test/java`.

2022-08-24 14:19 UTC, fooker commented on client/v2/src/main/test/java/org/opennms/velocloud/client/v2/VelocloudApiClientTest.java
Class name should be `VelocloudApiClientV2Test`

2022-08-24 14:19 UTC, fooker commented on plugin/src/main/java/org/opennms/velocloud/requisition/CustomerRequisitionProvider.java
> +
Additional whitespace

2022-08-24 16:51 UTC, amay94 commented
So if I understand this correctly, this is just moving the existing client designed for V2 of their API into `client/V2` and creating a V1 version with just the pom and swagger resources?

2022-08-24 18:02 UTC, aramosvizcarra commented
> So if I understand this correctly, this is just moving the existing client designed for V2 of their API into `client/V2` and creating a V1 version with just the pom and swagger resources?

Thats right. The resources are the json (v1) and yaml (V2) openapi filde descriptors for each API.
THere is also a new client/api module that will contain all the abstraction that should map to each client so they can be accessed seamlessly by the rest of the application.

2022-08-24 18:03 UTC, amay94 approved these changes
Looks good!

2022-08-25 12:58 UTC, fooker approved these changes

2022-08-25 13:03 UTC, merged